nohup: 入力を無視します
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/matplotlib/__init__.py:1067: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))
Traceback (most recent call last):
  File "lstm_word2vec_analysis_to1dim.py", line 426, in <module>
    make_model_and_train(hidden_dim,epoch_num,vad_type,learning_rate=lr,batch_size=bs,overwrite=False)
  File "lstm_word2vec_analysis_to1dim.py", line 345, in make_model_and_train
    loss_function = nn.L1Loss(reduction='sum')
TypeError: __init__() got an unexpected keyword argument 'reduction'
